version: '0.1'

services:
  nginx:
    restart: unless-stopped
    volumes:
      - certs:/etc/nginx/certs:ro
      - /etc/nginx/vhost.d
      - /usr/share/nginx/html
    ports:
      - "80:80"
      - "443:443"
  nginx-letsencrypt:
    restart: unless-stopped
    image: nginxproxy/acme-companion:2.5.2
    volumes_from:
      - nginx
    volumes:
      - certs:/etc/nginx/certs:rw
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /etc/acme.sh
    environment:
      DEFAULT_EMAIL: ${LETSENCRYPT_EMAIL:?}
    depends_on:
      - nginx

volumes:
  - certs: {}