
services:
  web-app:
    environment:
      FLASK_ENV: production
      VIRTUAL_HOST: ${HOST_DOMAIN}
      DATABASE_URL: postgresql://${DB_USER}:${DB_PASSWORD}@{DB_HOST}:5432/${DB_NAME}
  nginx:
    restart: unless-stopped
    volumes:
      - certs:/etc/nginx/certs:ro
      - vhost:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
    ports:
      - "80:80"
      - "443:443"
  nginx-letsencrypt:
    restart: unless-stopped
    image: nginxproxy/acme-companion:2.5.2
    depends_on:
      - nginx
    volumes:
      - data_static:/home/app/src/app/static:ro
      - cache_nginx:/var/cache/nginx
      - state_nginx:/etc/nginx
      - certs:/etc/nginx/certs:rw
      - vhost:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /etc/acme.sh
    environment:
      DEFAULT_EMAIL: ${LETSENCRYPT_EMAIL:?}

  postgres:
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}

volumes:
  certs: {}
  vhost: {}
  html: {}
  acme: {}